### ISSUE TITLE
“静态链接时的动态链接库”？

### ISSUE THREAD

**Issue by hshq** [Evian-Zhang/learn-assembly-on-Apple-Silicon-Mac#10]
第14章《[汇编、链接与调试](https://evian-zhang.github.io/learn-assembly-on-Apple-Silicon-Mac/14-%E6%B1%87%E7%BC%96%E3%80%81%E9%93%BE%E6%8E%A5%E4%B8%8E%E8%B0%83%E8%AF%95.html)》的《[静态链接时的动态链接库](https://evian-zhang.github.io/learn-assembly-on-Apple-Silicon-Mac/14-%E6%B1%87%E7%BC%96%E3%80%81%E9%93%BE%E6%8E%A5%E4%B8%8E%E8%B0%83%E8%AF%95.html#%E9%9D%99%E6%80%81%E9%93%BE%E6%8E%A5%E6%97%B6%E7%9A%84%E5%8A%A8%E6%80%81%E9%93%BE%E6%8E%A5%E5%BA%93)》这一节中，“查看一个动态链接的程序内记录的动态链接库的名字”这一句看懂了，其他几处提到“静态链接”没看懂，而且`14-main-dynamic`是”动态链接“的，所以这节那几处”静态链接“都应该是”动态链接“？

**Comment by Evian-Zhang** [comment]
这里我确实用词不太准确，已修改，感谢：）

这里的「静态链接」指的是“编译->链接->可执行程序”这一过程中的链接阶段（也就是在可执行程序生成的时候，运行它之前），但如果直接说「链接」，又有可能让人理解成静态链接和动态链接两个阶段，因此我这里修改成了编译链接。
