### ISSUE TITLE
may be a typing mistake

### ISSUE THREAD

**Issue by Tommy-Zhang3759** [Evian-Zhang/learn-assembly-on-Apple-Silicon-Mac#2]
.section
我们之前在操作系统一章中提到，Mach-0可执行文件的Data部分拥有许多段(Segment)，每个段又有许多
节(section). 同一个段的作用往往是类似的，同时在执行的时候一个段会被分配到一个页之中。
而.section 最常用的格式，就是
.section segname, sectname
其中 segment 是段名，sectname 是节名。我们目前编写的第一个汇编语言程序，只包含纯代码。

最后一行的segment是否应为segname？

**Comment by Evian-Zhang** [comment]
谢谢！已修改
