### ISSUE TITLE
shell 代码建议

### ISSUE THREAD

**Issue by hshq** [Evian-Zhang/learn-assembly-on-Apple-Silicon-Mac#8]
> \`xcrun --show-sdk-path -sdk macosx\`

fish 好像不支持这种简写语法，

> $(xcrun --show-sdk-path -sdk macosx)

没问题，这应该是通用的语法吧。

----来自 fish 非资深用户。

**Comment by Evian-Zhang** [comment]
我用fish试了一下，fish似乎既不支持$()也不支持``这种，而是得用()才行。POSIX Shell通用的方式似乎是$()和``皆可

**Comment by hshq** [comment]
我这里确实可以，$() 和 只 () 都可以，机器是 m2 mac mini ，系统 14.1.1 (23B81)。

<img width="681" alt="截屏2023-11-17 16 03 29" src="https://github.com/Evian-Zhang/learn-assembly-on-Apple-Silicon-Mac/assets/32267/c660ef8d-ab3e-488c-8b7d-f27934fef270">

**Comment by Evian-Zhang** [comment]
[查了一下](https://fishshell.com/docs/current/tutorial.html#command-substitutions)，fish 3.4.0之后支持了$()语法。感谢指正！
