### ISSUE TITLE
勘误：第九章有符号除法指令

### ISSUE THREAD

**Issue by hshq** [Evian-Zhang/learn-assembly-on-Apple-Silicon-Mac#9]
第九章有符号除法指令的举例：

> 对-5和-2进行`sdiv`，得到的是-2

结果应该是 **2** 吧

<img width="330" alt="截屏2023-11-17 23 12 45" src="https://github.com/Evian-Zhang/learn-assembly-on-Apple-Silicon-Mac/assets/32267/d5c4c297-1e64-40bc-8b80-c152691821f2">

**Comment by Evian-Zhang** [comment]
感谢指正！
